server:
  port: 9090
  
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3307/electronics
    username: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true  
    